version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mr_cleaner
  front:
    build: ./mr-cleaner-front
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./mr-cleaner-api
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/mr_cleaner?schema=public"
      PORT: 4000
      JWT_SECRET: "mysecret123"
